name: Django CI # nombre del workflow

on: # triggers para el pipeline
  pull_request: # corre en los pullrequest a la main
    branches: [main]
  push: # corre con cualquier push

jobs:
  build:
    runs-on: ubuntu-latest # en que va a correr, linux ubuntu
    steps:
      - uses: actions/checkout@v4 # action predefinido, descarga el repositorio en la maquina linux
      - name: Set up Python 
        uses: actions/setup-python@v4 # action predefinido
        with:
          python-version: 3.10 # usando version especifica 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test